### PR TITLE
split up default writer

### PR DESCRIPTION
**Pull request by lsmith77**
see https://github.com/spatie/laravel-http-logger/issues/38

### CODE REVIEW

**Comment by lsmith77** [comment]
hmm not so experienced yet with GH, any idea why the tests failed?

**Comment by freekmurze** [comment]
There seems to be an undefined variables somewhere: https://github.com/spatie/laravel-http-logger/pull/39/checks?check_run_id=1637118973#step:5:39

**Comment by lsmith77** [comment]
ok looks better now. sorry about that.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
